[package]
name = "bf_compiler"
version = "0.1.0"
authors = ["horus-4ever"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strfmt = "0.1.6"